### ISSUE TITLE
Licenses for models

### ISSUE THREAD

**Issue by r0mainK** [src-d/models#3]
@marnovo  @eiso  @smola @mcuadros @vmarkovtsev 

Hey guys, I'm currently updating this repo, and adding the `id-split` model, however currently we have no licenses for any of the models (and the repo itself but [an issue](https://github.com/src-d/models/issues/1) is already open). Marcelo told me to add you guys to this so you could discuss it

There are no deadlines apart from the upcoming release of the paper  on `id-split` as well as the associated ML4P conference on the 18–19 July where it will be presented (unless paper gets rejected :trollface:)

**Comment by eiso** [comment]
@r0mainK let me get back to you on this soon asap.

**Comment by r0mainK** [comment]
@eiso any progress on this ? as soon as [this PR](https://github.com/src-d/modelforge/pull/25) gets merged Im gonna regenerate the repo, I know this is not an essential issue but afterwards focus will be on other stuff and it might be forgotten for some time

**Comment by eiso** [comment]
It is top of mind now, I will get back to you shortly.

**Comment by vmarkovtsev** [comment]
@eiso 1-month ping

**Comment by eiso** [comment]
We honestly don't know yet.

**Comment by vmarkovtsev** [comment]
We could pick something arbitrary and change later as we did with PGA

**Comment by eiso** [comment]
AGPL3 then.

**Comment by vmarkovtsev** [comment]
The license was settled at ODbL-1.0.
