### ISSUE TITLE
nbow link is broken

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/models#5]
README.md -> nbow -> a42a-28b6-4b33-94a2-a5671f4102f4

The link is 404

**Comment by r0mainK** [comment]
@vmarkovtsev found the bug, the `links` dict used in the template was not created right.
 - PR fix modelforge is here: https://github.com/src-d/modelforge/pull/40
 - PR for models : https://github.com/src-d/models/pull/6

**Comment by r0mainK** [comment]
can be closed
