### ISSUE TITLE
Add Bags features extracted from PGA

### ISSUE THREAD

**Issue by r0mainK** [src-d/models#7]
Pretty much all in title, I've extracted all possible features as of now out of PGA, while [running on apollo](https://github.com/src-d/backlog/issues/1196) and think it would be a good idea to publish the `bags.asdf` result, as well with the associated `docfreq.asdf` and `quant.asdf` models used to create it. It was a very long and painful process to do so, and I think there is a lot of value in this:

- for us it will be useful to have this dump available, be it to rerun apollo without going through the pain, or as features for later tasks
- for the community, same reasons, but also taking into account they might not have the knowledge or infra to extract all of these features out of PGA

I will link here to the PR and add metrics when I have them (currently in the process of merging the 460 batches into a single one, for obvious practical reasons and also to reduce size).

@vmarkovtsev wanted you to know @campoy in order for you to choose how we should release this. Since I am leaving soon I will create the PR and it will stay in this state until you give your okay. 

We could also publish the other models create via apollo using these, i.e. the `param.asdf`, `cc.asd` and `cmd.asdf` models resulting from, respectivelly, `apollo hash`, `apollo cc` and `apollo cmd` commands.

**Comment by vmarkovtsev** [comment]
Bag features is a valuable dataset which can be used to solve several funny problems. I am completely +1

**Comment by r0mainK** [comment]
Okay, will create the PR. I have used [this](https://github.com/src-d/ml/pull/295) to merge bags together but can't seem to merge in less then 3 parts, two of 25G and one of 5.5G (Python Kills the process when merging sparse matrices, I'm guessing OOM).

**Comment by r0mainK** [comment]
The PR: https://github.com/src-d/models/pull/8

**Comment by campoy** [comment]
The PR is actually #9

**Comment by r0mainK** [comment]
This is done for a while now, closing.
